
# All this information is gotten by loading FoE and watching the requests in the browser's developer console

# The version, secret and timestamp need to match and might change when the game updates
game:
    # Update this to match the server you are playing on
    server: de11
    # Inside the 'Client-Identification' header
    version: '1.219'
    # This can be gotten by following this tutorial: https://github.com/m3talstorm/foe-decryption
    secret: o8dHl2GcvQOPbndY/fp6crdorRfZPn7OCZM7SRsqUVgbqH8NGwarYhNo1SrAQtX2wVfvciOgTgIWVneTQCsqgA==
    # The timestamp inside of the 'Referer' header: https://foeen.innogamescdn.com/swf/Preloader.swf?<here>/[[DYNAMIC]]/1
    # Not used anymore
    timestamp: 1511779469

login:
    # This is the value https://<server>.forgeofempires.com/game/json?h=<user_key> in each request
    user_key: 'zpG9aUbZ-sQWFIBIBN1pjGoh'
    # This is the value of 'sid' inside the cookie of each request
    sid: 'nArCQoOVyKkKtf7mURR3ZOotUcweNZDeanXbi6VO'

settings:
    # How often the bot should do a full update
    update:
        min: 299
        max: 300
    # Who should the bot polish/motivate
    polivate:
        #
        friends: true
        #
        guild: true
        # If this is true then you won't be able to attack and plunder anyone
        neighbours: true
    #
    tavern:
        # If the bot should collect silver from your tavern
        collect: true
        # (WIP) The % of seats that should be in use before the bot collects the silver (the more people sitting the more silver you get per seat)
        threshold: 75
        # If the bot should try and sit in all friends taverns
        sit: true
    # What kinds of buildings the bot should collect from and start production
    resources:

        coins: true

        supplies: true

        random: true

        goods: false
    #
    goods:
        # (WIP) If the bot should try and balance goods through the aution house so the quantities are roughly the same
        balance: false
    #
    troops:
        # (WIP) If the bot should train all availible troop slots
        train: true
